# write a program to accept markes of 6 student a and desplay them in a sorted manned
marks=[]
f1=int(input("enter marks here : "))
marks.append(f1)
f2=int(input("enter marks here : "))
marks.append(f2)
f3=int(input("enter marks here : "))
marks.append(f3)
f4=int(input("enter marks here : "))
marks.append(f4)
f5=int(input("enter marks here : "))
marks.append(f5)
f6=int(input("enter marks here : "))
marks.append(f6)
print(marks)